GENERAL:
  seed: 2021
  log_path: ./logs
  ckpt_path: ./ckpts/exps
  wandb: True
  gpu: 0
  
TRAINING:
  batch_size: 8
  num_workers: 0
  optimizer: adam
  learning_rate: 1.0e-3
  num_epochs: 1000
  early_stopping:
    monitor: valid_neglike
    patience: 30
    mode: min
  
MODEL:
  latent_dim: 10
  loss_type: 'NegativeBinomial'
  prop: True
  prop_cls: 29
  warmupsteps: 2000

  # scvi_checkpoint_dir: /home/hdd/kazuya/bulk_trial/ckpts/scvi_nb
  # indexer_dir: /home/hdd/kazuya/bulk_trial/dataset/sc2bulk_geneidx.npy

DATASET:
  dataset: PropDataset
  testdataset: PropDataset
  collate_fn: collate_fn
  data_dir: ./dataset
  dir_name: sample_pair4mil
  
  


